#ifndef POINT_PRIMITIVE_GLOBAL_H
#define POINT_PRIMITIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POINT_PRIMITIVE_LIBRARY)
#  define POINT_PRIMITIVE_EXPORT Q_DECL_EXPORT
#else
#  define POINT_PRIMITIVE_EXPORT Q_DECL_IMPORT
#endif

#endif // POINT_PRIMITIVE_GLOBAL_H
