#ifndef ADD_POINT_EDIT_MODE_GLOBAL_H
#define ADD_POINT_EDIT_MODE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADDPOINTEDITMODE_LIBRARY)
#  define ADDPOINTEDITMODE_EXPORT Q_DECL_EXPORT
#else
#  define ADDPOINTEDITMODE_EXPORT Q_DECL_IMPORT
#endif

#endif // ADD_POINT_EDIT_MODE_GLOBAL_H
