#ifndef SCENE_SCHEME_VIEW_MODEL_GLOBAL_H
#define SCENE_SCHEME_VIEW_MODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCENE_SCHEME_VIEW_MODEL_LIBRARY)
#  define SCENE_SCHEME_VIEW_MODEL_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_SCHEME_VIEW_MODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_SCHEME_VIEW_MODEL_GLOBAL_H
