#ifndef POINT_PROPERTIES_COMPONENT_GLOBAL_H
#define POINT_PROPERTIES_COMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POINT_PROPERTIES_COMPONENT_LIBRARY)
#  define POINT_PROPERTIES_COMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define POINT_PROPERTIES_COMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // POINT_PROPERTIES_COMPONENT_GLOBAL_H
